/*
 * This source file was generated by the Gradle 'init' task
 */
package top.monkeyfans

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class KoalaGeneratorPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("top.monkeyfans.generator")

        assertNotNull(project.extensions.findByName("generator"))
        val extension = project.extensions.getByName("generator") as GeneratorExtension
        assertEquals("top.monkeyfans.entity", extension.entityPackageName.get())
        assertEquals("top.monkeyfans.dto", extension.dtoPackageName.get())
        assertEquals("Dto", extension.dtoClassSuffixName.get())
        assertEquals(GeneratorType.NORMAL_CLASS, extension.generatorType.get())
    }
}
