/*
 * This source file was generated by the Gradle 'init' task
 */
package top.monkeyfans

import java.io.File
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import kotlin.test.assertEquals

/**
 * A simple functional test for the 'org.example.greeting' plugin.
 */
class KoalaGeneratorPluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test
    fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText(
            """
            plugins {
                id('top.monkeyfans.generator')
            }
        """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("generator")
        runner.withProjectDir(projectDir)
        val result = runner.build()
    }
}
